In [1]:
import json
import pandas as pd

def jsons_to_df(json_paths, method_names, columns=None):
    rows = []
    
    for path, name in zip(json_paths, method_names):
        try:
            with open(path, "r") as f:
                d = json.load(f)
        except FileNotFoundError:
            print(f"File not found {name}: {path}")
            d = {col: None for col in columns} 
        d["method"] = name
        rows.append(d)
    
    df = pd.DataFrame(rows)
    
    if columns:
        df = df[["method"] + columns]
    
    display(df)
    # return df

columns = ['roc_auc_mean', 'roc_auc_std', 'accuracy_mean', 'accuracy_std']
method_names = ['Radiomics Attention Pooling', 'Radiomics Statistical Pooling', '2D images Googlenet', 'RPNet3D', "3D MTL Attention Siamese"]

In [2]:
json_paths = [
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/RadiomicsMIL/overall_survival_24m/shape_boundary_intensity_texture/fivefold_aggregated_results.json",
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/StatisticalPoolingMLP/overall_survival_24m/shape_boundary_intensity_texture/fivefold_aggregated_results.json",
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/GooglenetLSTM/overall_survival_24m/fivefold_aggregated_results.json",
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/RPNet3D/overall_survival_24m/fivefold_aggregated_results.json",
    "",
    ]
print("overall survival results:")
jsons_to_df(json_paths, method_names, columns)

overall survival results:
File not found 3D MTL Attention Siamese:

,method,roc_auc_mean,roc_auc_std,accuracy_mean,accuracy_std
0,Radiomics Attention Pooling,0.741168,0.031847,0.700837,0.030505
1,Radiomics Statistical Pooling,0.666709,0.052888,0.662046,0.046914
2,2D images Googlenet,0.612315,0.064886,0.599371,0.053629
3,RPNet3D,0.618470,0.079630,0.559496,0.067616
4,3D MTL Attention Siamese,NaN,NaN,NaN,NaN

In [3]:
json_paths = [
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/RadiomicsMIL/early_recurrence/shape_boundary_intensity_texture/fivefold_aggregated_results.json",
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/StatisticalPoolingMLP/early_recurrence/shape_boundary_intensity_texture/fivefold_aggregated_results.json",
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/GooglenetLSTM/early_recurrence/fivefold_aggregated_results.json",
    "",
    "",
    ]
print("early recurrence results:")
jsons_to_df(json_paths, method_names, columns)

early recurrence results:
File not found RPNet3D:
File not found 3D MTL Attention Siamese:

,method,roc_auc_mean,roc_auc_std,accuracy_mean,accuracy_std
0,Radiomics Attention Pooling,0.627117,0.071944,0.525238,0.090340
1,Radiomics Statistical Pooling,0.701523,0.074387,0.624897,0.083632
2,2D images Googlenet,0.586581,0.038871,0.575901,0.056455
3,RPNet3D,NaN,NaN,NaN,NaN
4,3D MTL Attention Siamese,NaN,NaN,NaN,NaN

In [4]:
json_paths = [
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/RadiomicsMIL/morph_response/shape_boundary_intensity_texture/fivefold_aggregated_results.json",
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/StatisticalPoolingMLP/morph_response/shape_boundary_intensity_texture/fivefold_aggregated_results.json",
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/GooglenetLSTM/morph_response/fivefold_aggregated_results.json",
    "",
    "",
    ]
print("morphology response results (3 classes):")
jsons_to_df(json_paths, method_names, columns)

morphology response results (3 classes):
File not found RPNet3D:
File not found 3D MTL Attention Siamese:

,method,roc_auc_mean,roc_auc_std,accuracy_mean,accuracy_std
0,Radiomics Attention Pooling,0.541777,0.065109,0.356527,0.165792
1,Radiomics Statistical Pooling,0.556834,0.032287,0.447273,0.092426
2,2D images Googlenet,0.490603,0.025995,0.336791,0.122971
3,RPNet3D,NaN,NaN,NaN,NaN
4,3D MTL Attention Siamese,NaN,NaN,NaN,NaN

In [5]:
json_paths = [
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/RadiomicsMIL/pathology/shape_boundary_intensity_texture/fivefold_aggregated_results.json",
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/StatisticalPoolingMLP/pathology/shape_boundary_intensity_texture/fivefold_aggregated_results.json",
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/GooglenetLSTM/pathology/fivefold_aggregated_results.json",
    "",
    "",
    ]
print("pathologye results:")
jsons_to_df(json_paths, method_names, columns)

pathologye results:
File not found RPNet3D:
File not found 3D MTL Attention Siamese:

,method,roc_auc_mean,roc_auc_std,accuracy_mean,accuracy_std
0,Radiomics Attention Pooling,0.635811,0.096569,0.601678,0.052463
1,Radiomics Statistical Pooling,0.643909,0.073541,0.616918,0.052763
2,2D images Googlenet,0.510597,0.075070,0.506651,0.062242
3,RPNet3D,NaN,NaN,NaN,NaN
4,3D MTL Attention Siamese,NaN,NaN,NaN,NaN

In [6]:
json_paths = [
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/MorphScoreRadiomicsMIL/shape_boundary_intensity_texture/fivefold_aggregated_results.json",
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/MorphScoreStatisticalPoolingMLP/shape_boundary_intensity_texture/fivefold_aggregated_results.json",
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/MorphScoreGooglenetLSTM/fivefold_aggregated_results.json",
    "",
    "",
    ]
print("morphology score results (3 classes):")
method_names = ['MorphScore RadiomicsMIL (all features)', 'MorphScore StatisticalPoolingMLP (all features)', 'MorphScore GooglenetLSTM', "RPNet3D", "3D MTL Attention Siamese"]
jsons_to_df(json_paths, method_names, columns)

morphology score results (3 classes):

File not found RPNet3D:
File not found 3D MTL Attention Siamese:

,method,roc_auc_mean,roc_auc_std,accuracy_mean,accuracy_std
0,MorphScore RadiomicsMIL (all features),0.566138,0.034677,0.359290,0.083090
1,MorphScore StatisticalPoolingMLP (all features),0.558092,0.047438,0.401707,0.054343
2,MorphScore GooglenetLSTM,0.570732,0.083068,0.346346,0.110765
3,RPNet3D,NaN,NaN,NaN,NaN
4,3D MTL Attention Siamese,NaN,NaN,NaN,NaN

In [7]:
json_paths = [
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/MorphScoreStatisticalPoolingMLP/shape_boundary_intensity_texture/fivefold_aggregated_results.json",
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/MorphScoreStatisticalPoolingMLP/boundary_intensity_texture/fivefold_aggregated_results.json",
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/MorphScoreStatisticalPoolingMLP/shape_intensity_texture/fivefold_aggregated_results.json",
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/MorphScoreStatisticalPoolingMLP/shape_boundary_texture/fivefold_aggregated_results.json",
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/MorphScoreStatisticalPoolingMLP/shape_boundary_intensity/fivefold_aggregated_results.json",
    ]
print("morphology score results (3 classes):")
method_names = ['StatisticalPoolingMLP (all features)', 
                'StatisticalPoolingMLP (boundary_intensity_texture)', 
                'StatisticalPoolingMLP (shape_intensity_texture)', 
                'StatisticalPoolingMLP (shape_boundary_texture)', 
                'StatisticalPoolingMLP (shape_boundary_intensity)']
jsons_to_df(json_paths, method_names, columns)

morphology score results (3 classes):

,method,roc_auc_mean,roc_auc_std,accuracy_mean,accuracy_std
0,StatisticalPoolingMLP (all features),0.558092,0.047438,0.401707,0.054343
1,StatisticalPoolingMLP (boundary_intensity_text...,0.568466,0.024756,0.379981,0.092186
2,StatisticalPoolingMLP (shape_intensity_texture),0.559785,0.035537,0.345622,0.121751
3,StatisticalPoolingMLP (shape_boundary_texture),0.577589,0.055358,0.390711,0.105230
4,StatisticalPoolingMLP (shape_boundary_intensity),0.591919,0.029522,0.389646,0.058068

In [8]:
json_paths = [
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/MorphScoreStatisticalPoolingMLP/shape/fivefold_aggregated_results.json",
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/MorphScoreStatisticalPoolingMLP/boundary/fivefold_aggregated_results.json",
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/MorphScoreStatisticalPoolingMLP/intensity/fivefold_aggregated_results.json",
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/MorphScoreStatisticalPoolingMLP/texture/fivefold_aggregated_results.json",
    ]
print("morphology score results (3 classes):")
method_names = [
                'StatisticalPoolingMLP (shape)', 
                'StatisticalPoolingMLP (boundary)', 
                'StatisticalPoolingMLP (intensity)', 
                'StatisticalPoolingMLP (texture)']
jsons_to_df(json_paths, method_names, columns)

morphology score results (3 classes):

,method,roc_auc_mean,roc_auc_std,accuracy_mean,accuracy_std
0,StatisticalPoolingMLP (shape),0.582806,0.043387,0.450952,0.041049
1,StatisticalPoolingMLP (boundary),0.577271,0.027504,0.428684,0.044922
2,StatisticalPoolingMLP (intensity),0.576186,0.071324,0.418784,0.095452
3,StatisticalPoolingMLP (texture),0.528454,0.025809,0.324585,0.097208

## MIL

In [11]:
json_paths = [
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/MorphScoreRadiomicsMIL/shape_boundary_intensity_texture/fivefold_aggregated_results.json",
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/MorphScoreRadiomicsMIL/boundary_intensity_texture/fivefold_aggregated_results.json",
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/MorphScoreRadiomicsMIL/shape_intensity_texture/fivefold_aggregated_results.json",
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/MorphScoreRadiomicsMIL/shape_boundary_texture/fivefold_aggregated_results.json",
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/MorphScoreRadiomicsMIL/shape_boundary_intensity/fivefold_aggregated_results.json",
    ]
print("morphology score results (3 classes):")
method_names = ['MIL (all features)', 
                'MIL (boundary_intensity_texture)', 
                'MIL (shape_intensity_texture)', 
                'MIL (shape_boundary_texture)', 
                'MIL (shape_boundary_intensity)']
jsons_to_df(json_paths, method_names, columns)

morphology score results (3 classes):

,method,roc_auc_mean,roc_auc_std,accuracy_mean,accuracy_std
0,MIL (all features),0.565482,0.036756,0.427256,0.091931
1,MIL (boundary_intensity_texture),0.539950,0.035102,0.389424,0.064114
2,MIL (shape_intensity_texture),0.560620,0.042933,0.452082,0.040612
3,MIL (shape_boundary_texture),0.565850,0.033375,0.387060,0.082689
4,MIL (shape_boundary_intensity),0.561456,0.041755,0.373945,0.053681

In [12]:
json_paths = [
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/MorphScoreRadiomicsMIL/shape/fivefold_aggregated_results.json",
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/MorphScoreRadiomicsMIL/boundary/fivefold_aggregated_results.json",
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/MorphScoreRadiomicsMIL/intensity/fivefold_aggregated_results.json",
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/MorphScoreRadiomicsMIL/texture/fivefold_aggregated_results.json",
    ]
print("morphology score results (3 classes):")
method_names = [
                'RadiomicsMIL (shape)', 
                'RadiomicsMIL (boundary)', 
                'RadiomicsMIL (intensity)', 
                'RadiomicsMIL (texture)']
jsons_to_df(json_paths, method_names, columns)

morphology score results (3 classes):

,method,roc_auc_mean,roc_auc_std,accuracy_mean,accuracy_std
0,RadiomicsMIL (shape),0.559591,0.031892,0.421266,0.089573
1,RadiomicsMIL (boundary),0.567396,0.039109,0.407729,0.061468
2,RadiomicsMIL (intensity),0.521432,0.031436,0.371011,0.034806
3,RadiomicsMIL (texture),0.536297,0.039036,0.351402,0.065361