In [1]:
import json
import pandas as pd

def jsons_to_df(json_paths, method_names, columns=None):
    rows = []
    
    for path, name in zip(json_paths, method_names):
        try:
            with open(path, "r") as f:
                d = json.load(f)
        except FileNotFoundError:
            print(f"File not found {name}: {path}")
            d = {col: None for col in columns} 
        d["method"] = name
        rows.append(d)
    
    df = pd.DataFrame(rows)
    
    if columns:
        df = df[["method"] + columns]
    
    display(df)
    # return df

columns = ['roc_auc_mean', 'roc_auc_std', 'accuracy_mean', 'accuracy_std']
method_names = ['Radiomics Attention Pooling', 'Radiomics Statistical Pooling', '2D images Googlenet', 'RPNet3D', "3D MTL Attention Siamese"]

In [2]:
json_paths = [
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/RadiomicsMIL/overall_survival_24m/shape_boundary_intensity_texture/fivefold_aggregated_results.json",
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/StatisticalPoolingMLP/overall_survival_24m/shape_boundary_intensity_texture/fivefold_aggregated_results.json",
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/GooglenetLSTM/overall_survival_24m/fivefold_aggregated_results.json",
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/RPNet3D/overall_survival_24m/fivefold_aggregated_results.json",
    "",
    ]
print("overall survival results:")
jsons_to_df(json_paths, method_names, columns)

overall survival results:
File not found 3D MTL Attention Siamese:

,method,roc_auc_mean,roc_auc_std,accuracy_mean,accuracy_std
0,Radiomics Attention Pooling,0.741556,0.034693,0.710594,0.037687
1,Radiomics Statistical Pooling,0.673124,0.081794,0.625397,0.050261
2,2D images Googlenet,0.656022,0.062588,0.628172,0.045039
3,RPNet3D,0.618470,0.079630,0.559496,0.067616
4,3D MTL Attention Siamese,NaN,NaN,NaN,NaN

In [3]:
json_paths = [
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/RadiomicsMIL/early_recurrence/shape_boundary_intensity_texture/fivefold_aggregated_results.json",
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/StatisticalPoolingMLP/early_recurrence/shape_boundary_intensity_texture/fivefold_aggregated_results.json",
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/GooglenetLSTM/early_recurrence/fivefold_aggregated_results.json",
    "",
    "",
    ]
print("early recurrence results:")
jsons_to_df(json_paths, method_names, columns)

early recurrence results:
File not found RPNet3D:
File not found 3D MTL Attention Siamese:

,method,roc_auc_mean,roc_auc_std,accuracy_mean,accuracy_std
0,Radiomics Attention Pooling,0.652296,0.046876,0.528245,0.055108
1,Radiomics Statistical Pooling,0.703593,0.070600,0.627485,0.077048
2,2D images Googlenet,0.570834,0.044540,0.555892,0.089715
3,RPNet3D,NaN,NaN,NaN,NaN
4,3D MTL Attention Siamese,NaN,NaN,NaN,NaN

In [4]:
json_paths = [
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/RadiomicsMIL/morph_response/shape_boundary_intensity_texture/fivefold_aggregated_results.json",
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/StatisticalPoolingMLP/morph_response/shape_boundary_intensity_texture/fivefold_aggregated_results.json",
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/GooglenetLSTM/morph_response/fivefold_aggregated_results.json",
    "",
    "",
    ]
print("morphology response results (3 classes):")
jsons_to_df(json_paths, method_names, columns)

morphology response results (3 classes):
File not found RPNet3D:
File not found 3D MTL Attention Siamese:

,method,roc_auc_mean,roc_auc_std,accuracy_mean,accuracy_std
0,Radiomics Attention Pooling,0.554182,0.044965,0.383518,0.093554
1,Radiomics Statistical Pooling,0.546242,0.023595,0.409946,0.085947
2,2D images Googlenet,0.549146,0.051689,0.435928,0.137905
3,RPNet3D,NaN,NaN,NaN,NaN
4,3D MTL Attention Siamese,NaN,NaN,NaN,NaN

In [ ]:
json_paths = [
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/RadiomicsMIL/pathology/shape_boundary_intensity_texture/fivefold_aggregated_results.json",
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/StatisticalPoolingMLP/pathology/shape_boundary_intensity_texture/fivefold_aggregated_results.json",
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/GooglenetLSTM/pathology/fivefold_aggregated_results.json",
    "",
    "",
    ]
print("pathology results:")
jsons_to_df(json_paths, method_names, columns)

pathologye results:
File not found RPNet3D:
File not found 3D MTL Attention Siamese:

,method,roc_auc_mean,roc_auc_std,accuracy_mean,accuracy_std
0,Radiomics Attention Pooling,0.635184,0.112620,0.587209,0.079473
1,Radiomics Statistical Pooling,0.614471,0.055163,0.581959,0.033956
2,2D images Googlenet,0.585261,0.073997,0.549057,0.065545
3,RPNet3D,NaN,NaN,NaN,NaN
4,3D MTL Attention Siamese,NaN,NaN,NaN,NaN

In [6]:
json_paths = [
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/MorphScoreRadiomicsMIL/shape_boundary_intensity_texture/fivefold_aggregated_results.json",
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/MorphScoreStatisticalPoolingMLP/shape_boundary_intensity_texture/fivefold_aggregated_results.json",
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/MorphScoreGooglenetLSTM/fivefold_aggregated_results.json",
    "",
    "",
    ]
print("morphology score results (3 classes):")
method_names = ['MorphScore RadiomicsMIL (all features)', 'MorphScore StatisticalPoolingMLP (all features)', 'MorphScore GooglenetLSTM', "RPNet3D", "3D MTL Attention Siamese"]
jsons_to_df(json_paths, method_names, columns)

morphology score results (3 classes):
File not found RPNet3D:
File not found 3D MTL Attention Siamese:

,method,roc_auc_mean,roc_auc_std,accuracy_mean,accuracy_std
0,MorphScore RadiomicsMIL (all features),0.551342,0.022462,0.348021,0.085555
1,MorphScore StatisticalPoolingMLP (all features),0.558092,0.047438,0.401707,0.054343
2,MorphScore GooglenetLSTM,0.558728,0.055488,0.438374,0.046953
3,RPNet3D,NaN,NaN,NaN,NaN
4,3D MTL Attention Siamese,NaN,NaN,NaN,NaN

In [7]:
json_paths = [
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/MorphScoreStatisticalPoolingMLP/shape_boundary_intensity_texture/fivefold_aggregated_results.json",
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/MorphScoreStatisticalPoolingMLP/boundary_intensity_texture/fivefold_aggregated_results.json",
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/MorphScoreStatisticalPoolingMLP/shape_intensity_texture/fivefold_aggregated_results.json",
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/MorphScoreStatisticalPoolingMLP/shape_boundary_texture/fivefold_aggregated_results.json",
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/MorphScoreStatisticalPoolingMLP/shape_boundary_intensity/fivefold_aggregated_results.json",
    ]
print("morphology score results (3 classes):")
method_names = ['StatisticalPoolingMLP (all features)', 
                'StatisticalPoolingMLP (boundary_intensity_texture)', 
                'StatisticalPoolingMLP (shape_intensity_texture)', 
                'StatisticalPoolingMLP (shape_boundary_texture)', 
                'StatisticalPoolingMLP (shape_boundary_intensity)']
jsons_to_df(json_paths, method_names, columns)

morphology score results (3 classes):

,method,roc_auc_mean,roc_auc_std,accuracy_mean,accuracy_std
0,StatisticalPoolingMLP (all features),0.558092,0.047438,0.401707,0.054343
1,StatisticalPoolingMLP (boundary_intensity_text...,0.568466,0.024756,0.379981,0.092186
2,StatisticalPoolingMLP (shape_intensity_texture),0.559785,0.035537,0.345622,0.121751
3,StatisticalPoolingMLP (shape_boundary_texture),0.577589,0.055358,0.390711,0.105230
4,StatisticalPoolingMLP (shape_boundary_intensity),0.591919,0.029522,0.389646,0.058068

In [8]:
json_paths = [
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/MorphScoreStatisticalPoolingMLP/shape/fivefold_aggregated_results.json",
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/MorphScoreStatisticalPoolingMLP/boundary/fivefold_aggregated_results.json",
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/MorphScoreStatisticalPoolingMLP/intensity/fivefold_aggregated_results.json",
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/MorphScoreStatisticalPoolingMLP/texture/fivefold_aggregated_results.json",
    ]
print("morphology score results (3 classes):")
method_names = [
                'StatisticalPoolingMLP (shape)', 
                'StatisticalPoolingMLP (boundary)', 
                'StatisticalPoolingMLP (intensity)', 
                'StatisticalPoolingMLP (texture)']
jsons_to_df(json_paths, method_names, columns)

morphology score results (3 classes):

,method,roc_auc_mean,roc_auc_std,accuracy_mean,accuracy_std
0,StatisticalPoolingMLP (shape),0.582806,0.043387,0.450952,0.041049
1,StatisticalPoolingMLP (boundary),0.577271,0.027504,0.428684,0.044922
2,StatisticalPoolingMLP (intensity),0.576186,0.071324,0.418784,0.095452
3,StatisticalPoolingMLP (texture),0.528454,0.025809,0.324585,0.097208

## MIL

In [9]:
json_paths = [
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/MorphScoreRadiomicsMIL/shape_boundary_intensity_texture/fivefold_aggregated_results.json",
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/MorphScoreRadiomicsMIL/boundary_intensity_texture/fivefold_aggregated_results.json",
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/MorphScoreRadiomicsMIL/shape_intensity_texture/fivefold_aggregated_results.json",
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/MorphScoreRadiomicsMIL/shape_boundary_texture/fivefold_aggregated_results.json",
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/MorphScoreRadiomicsMIL/shape_boundary_intensity/fivefold_aggregated_results.json",
    ]
print("morphology score results (3 classes):")
method_names = ['MIL (all features)', 
                'MIL (boundary_intensity_texture)', 
                'MIL (shape_intensity_texture)', 
                'MIL (shape_boundary_texture)', 
                'MIL (shape_boundary_intensity)']
jsons_to_df(json_paths, method_names, columns)

morphology score results (3 classes):

,method,roc_auc_mean,roc_auc_std,accuracy_mean,accuracy_std
0,MIL (all features),0.551342,0.022462,0.348021,0.085555
1,MIL (boundary_intensity_texture),0.539950,0.035102,0.389424,0.064114
2,MIL (shape_intensity_texture),0.560620,0.042933,0.452082,0.040612
3,MIL (shape_boundary_texture),0.540371,0.047286,0.379498,0.110336
4,MIL (shape_boundary_intensity),0.567779,0.049525,0.408415,0.107566

In [10]:
json_paths = [
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/MorphScoreRadiomicsMIL/shape/fivefold_aggregated_results.json",
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/MorphScoreRadiomicsMIL/boundary/fivefold_aggregated_results.json",
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/MorphScoreRadiomicsMIL/intensity/fivefold_aggregated_results.json",
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/MorphScoreRadiomicsMIL/texture/fivefold_aggregated_results.json",
    ]
print("morphology score results (3 classes):")
method_names = [
                'RadiomicsMIL (shape)', 
                'RadiomicsMIL (boundary)', 
                'RadiomicsMIL (intensity)', 
                'RadiomicsMIL (texture)']
jsons_to_df(json_paths, method_names, columns)

morphology score results (3 classes):

,method,roc_auc_mean,roc_auc_std,accuracy_mean,accuracy_std
0,RadiomicsMIL (shape),0.552853,0.038604,0.396273,0.038260
1,RadiomicsMIL (boundary),0.567396,0.039109,0.407729,0.061468
2,RadiomicsMIL (intensity),0.555989,0.025320,0.408681,0.087534
3,RadiomicsMIL (texture),0.536297,0.039036,0.351402,0.065361