In [19]:
import json
import pandas as pd

def jsons_to_df(json_paths, method_names, columns=None):
    rows = []
    
    for path, name in zip(json_paths, method_names):
        with open(path, "r") as f:
            d = json.load(f)
        d["method"] = name
        rows.append(d)
    
    df = pd.DataFrame(rows)
    
    if columns:
        df = df[["method"] + columns]
    
    display(df)
    # return df

columns = ['roc_auc_mean', 'roc_auc_std', 'accuracy_mean', 'accuracy_std']

In [20]:
json_paths = [
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/RadiomicsMIL/overall_survival_24m/shape_boundary_intensity_texture/fivefold_aggregated_results.json",
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/StatisticalPoolingMLP/overall_survival_24m/shape_boundary_intensity_texture/fivefold_aggregated_results.json",
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/GooglenetLSTM/overall_survival_24m/fivefold_aggregated_results.json",
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/RPNet3D/overall_survival_24m/fivefold_aggregated_results.json"
    ]
method_names = ['RadiomicsMIL', 'StatisticalPoolingMLP', 'GooglenetLSTM', 'RPNet3D']
print("overall survival results:")
jsons_to_df(json_paths, method_names, columns)

overall survival results:

,method,roc_auc_mean,roc_auc_std,accuracy_mean,accuracy_std
0,RadiomicsMIL,0.683450,0.063191,0.669304,0.029990
1,StatisticalPoolingMLP,0.643699,0.070298,0.652140,0.043375
2,GooglenetLSTM,0.612315,0.064886,0.599371,0.053629
3,RPNet3D,0.618470,0.079630,0.559496,0.067616

In [21]:
json_paths = [
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/RadiomicsMIL/early_recurrence/shape_boundary_intensity_texture/fivefold_aggregated_results.json",
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/StatisticalPoolingMLP/early_recurrence/shape_boundary_intensity_texture/fivefold_aggregated_results.json",
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/GooglenetLSTM/early_recurrence/fivefold_aggregated_results.json",
    ]
method_names = ['RadiomicsMIL', 'StatisticalPoolingMLP', 'GooglenetLSTM']
print("early recurrence results:")
jsons_to_df(json_paths, method_names, columns)

early recurrence results:

,method,roc_auc_mean,roc_auc_std,accuracy_mean,accuracy_std
0,RadiomicsMIL,0.597661,0.030363,0.510906,0.073076
1,StatisticalPoolingMLP,0.648638,0.058590,0.594107,0.080775
2,GooglenetLSTM,0.586581,0.038871,0.575901,0.056455

In [22]:
json_paths = [
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/RadiomicsMIL/morph_response/shape_boundary_intensity_texture/fivefold_aggregated_results.json",
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/StatisticalPoolingMLP/morph_response/shape_boundary_intensity_texture/fivefold_aggregated_results.json",
    ]
method_names = ['RadiomicsMIL', 'StatisticalPoolingMLP']
print("morphology response results (3 classes):")
jsons_to_df(json_paths, method_names, columns)

morphology response results (3 classes):

,method,roc_auc_mean,roc_auc_std,accuracy_mean,accuracy_std
0,RadiomicsMIL,0.510709,0.05945,0.376567,0.103296
1,StatisticalPoolingMLP,0.529399,0.03418,0.366114,0.098794

In [23]:
json_paths = [
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/RadiomicsMIL/pathology/shape_boundary_intensity_texture/fivefold_aggregated_results.json",
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/StatisticalPoolingMLP/pathology/shape_boundary_intensity_texture/fivefold_aggregated_results.json",
    ]
method_names = ['RadiomicsMIL', 'StatisticalPoolingMLP']
print("pathologye results:")
jsons_to_df(json_paths, method_names, columns)

pathologye results:

,method,roc_auc_mean,roc_auc_std,accuracy_mean,accuracy_std
0,RadiomicsMIL,0.522525,0.040022,0.560530,0.028296
1,StatisticalPoolingMLP,0.552915,0.098536,0.569109,0.064655

In [24]:
json_paths = [
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/MorphScoreRadiomicsMIL/shape_boundary_intensity_texture/fivefold_aggregated_results.json",
    "/mnt/l/Basic/divi/jstoker/slicer_pdac/Marius/Reza Morphology/codes/Results/MorphScoreStatisticalPoolingMLP/shape_boundary_intensity_texture/fivefold_aggregated_results.json",
    ]
method_names = ['MorphScoreRadiomicsMIL', 'MorphScoreStatisticalPoolingMLP']
print("morphology score results (3 classes):")
jsons_to_df(json_paths, method_names, columns)

morphology score results (3 classes):

,method,roc_auc_mean,roc_auc_std,accuracy_mean,accuracy_std
0,MorphScoreRadiomicsMIL,0.528555,0.037069,0.271744,0.119958
1,MorphScoreStatisticalPoolingMLP,0.528456,0.034668,0.399380,0.073733